### ISSUE TITLE
Support for clustering

### ISSUE THREAD

**Issue by arialdomartini** [luiscoms/openshift-rabbitmq#2]
Hi @luiscoms, amazing job, thank you!

I wonder if this image can be used to setup a cluster, without using any shared, persistent storage. Ideally, I would like to spin up a number of pods and see all of them to be part of the same cluster. As far as I verified, this doesn't happen, and all the pods are isolated, no matter if they have the same `ERLANG_COOKIE` or `RABBITMQ_ERLANG_COOKIE`.

I saw that you mention clustering in [docker-entrypoint.sh](https://github.com/luiscoms/openshift-rabbitmq/blob/a7ad292b38864975afa862a477d106b4c1f148a0/docker-entrypoint.sh#L273-L278), but as far as I see there's no direct cal to `rabbitmqctl join_cluster` in the code, so I suppose there's no support for clustering.

Do you have any hints, or any plans to support clustering in the future? I am willing to collaborate with some pull requests, but as the first step I'm double checking your plans on this topic.

Grazie!

**Comment by luiscoms** [comment]
Hi @arialdomartini , this image is based on Oficial rabbitmq image. The clustering mode is described there.
You can get some hints on original [docker-entrypoint.sh](https://github.com/docker-library/rabbitmq/blob/master/3.6/debian/docker-entrypoint.sh) 
I`m glad to merge your pull requests in the future.
